// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArdvi7PpIf3hhRUnU9dJUP24sajzku1js',
    appId: '1:861516935424:web:e6287f3fe7765f30b283e5',
    messagingSenderId: '861516935424',
    projectId: 'quizapp-c367b',
    authDomain: 'quizapp-c367b.firebaseapp.com',
    storageBucket: 'quizapp-c367b.appspot.com',
    measurementId: 'G-D91ETLTCLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-eSQF7cOQQoZItkTJTtt5ju3fboldLvY',
    appId: '1:861516935424:android:06e5ff69e0b1a5d3b283e5',
    messagingSenderId: '861516935424',
    projectId: 'quizapp-c367b',
    storageBucket: 'quizapp-c367b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA23rxZ6qqavx1R_TJAV1LoWf-5kLffiLw',
    appId: '1:861516935424:ios:6c53f5cb11166dd5b283e5',
    messagingSenderId: '861516935424',
    projectId: 'quizapp-c367b',
    storageBucket: 'quizapp-c367b.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA23rxZ6qqavx1R_TJAV1LoWf-5kLffiLw',
    appId: '1:861516935424:ios:554008997ab7908bb283e5',
    messagingSenderId: '861516935424',
    projectId: 'quizapp-c367b',
    storageBucket: 'quizapp-c367b.appspot.com',
    iosBundleId: 'com.example.quizapp.RunnerTests',
  );
}
